# Generated by Django 3.2.9 on 2021-12-06 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffee',
            options={'verbose_name': '咖啡', 'verbose_name_plural': '咖啡'},
        ),
        migrations.AddField(
            model_name='coffee',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grinding',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grinding',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
